### ISSUE TITLE
update variables, and env var to support new auto_update flag

### ISSUE THREAD

**Issue by abuxton** [redeux/terraform-kubernetes-terraform-cloud-agent#6]
updating the agent now supports 3 string literalls, https://www.terraform.io/cloud-docs/agents#updating 
['minor,patch,disable] and the variable name as changed TFC_AGENT_AUTO_UPDATE, it can also be done using a -auto-update flag

update to code base and related README to support new variable an env var in k8s deployment.

**Comment by amitsikka** [comment]
Do we have an update on this issue?
We are facing the same.

**Comment by redeux** [comment]
Yes, thanks for bringing this back to the top for me. I'll take a look at it this week.

**Comment by amitsikka** [comment]
Thanks @redeux for merging the PR.
Do you mind creating the release and tag ?

**Comment by redeux** [comment]
The new version is now available on the registry.
