### ISSUE TITLE
Could not download module "tfc_agents" on a windows client

### ISSUE THREAD

**Issue by martijnvdp** [redeux/terraform-kubernetes-terraform-cloud-agent#9]
Cant download the module on a windows client due the file in the examples folder :
error: invalid path 'examples/default/*.auto.tfvars.example'
```hcl
│ Error: Failed to download module
│
│ Could not download module "tfc_agents" (eks.tf:239) source code from "git::https://github.com/redeux/terraform-kubernetes-terraform-cloud-agent?ref=v0.1.0": error downloading
│ 'https://github.com/redeux/terraform-kubernetes-terraform-cloud-agent?ref=v0.1.0': C:\Program Files\Git\cmd\git.exe exited with 128: Cloning into '.terraform\modules\tfc_agents'...
│ error: invalid path 'examples/default/*.auto.tfvars.example'
│ fatal: unable to checkout working tree
│ warning: Clone succeeded, but checkout failed.
│ You can inspect what was checked out with 'git status'
│ and retry with 'git restore --source=HEAD :/'
```

**Comment by redeux** [comment]
Interesting. Thanks for reporting Martijn. 

Strange that it's happening for v0.1.0, which didn't include the example. I'll see if I can find a way to work around it without yanking the example. I don't have a windows box currently, but I'll see if I can replicate it on macOS or Linux.

**Comment by martijnvdp** [comment]
on windows you cant have a filename starting with an * , so a simple rename of the file woould fix it
